["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "./lib"

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
ZkPadFaucet = [
    "contracts/ZkPadFaucet.cairo",
]
ZkPadINOContract = [
    "contracts/ZkPadINOContract.cairo",
]
ZkPadIDOContract = [
    "contracts/ZkPadIDOContract.cairo",
]
ZkPadIDOFactory = [
    "contracts/ZkPadIDOFactory.cairo",
]
ZkPadLotteryToken = [
    "contracts/ZkPadLotteryToken.cairo",
]
ZkPadStaking = [
    "contracts/ZkPadStaking.cairo",
]
ZkPadTask = [
    "contracts/ZkPadTask.cairo",
]
ZkPadToken = [
    "contracts/ZkPadTask.cairo",
]
ZkPadVaultHarvestTask = [
    "contracts/ZkPadVaultHarvestTask.cairo",
]
