["protostar.config"]
protostar_version = "0.3.1"

["protostar.project"]
libs_path = "./lib"

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
AstralyFaucet = [
    "contracts/AstralyFaucet.cairo",
]
AstralyINOContract = [
    "contracts/AstralyINOContract.cairo",
]
AstralyIDOContract = [
    "contracts/AstralyIDOContract.cairo",
]
AstralyIDOFactory = [
    "contracts/AstralyIDOFactory.cairo",
]
AstralyLotteryToken = [
    "contracts/AstralyLotteryToken.cairo",
]
AstralyStaking = [
    "contracts/AstralyStaking.cairo",
]
AstralyTask = [
    "contracts/AstralyTask.cairo",
]
AstralyToken = [
    "contracts/AstralyTask.cairo",
]
AstralyVaultHarvestTask = [
    "contracts/AstralyVaultHarvestTask.cairo",
]
JediSwapWrapper = [
    "contracts/AMMs/jedi_swap/JediSwapWrapper.cairo",
]
